### ISSUE TITLE
Status of 2014 SDK

### ISSUE THREAD

**Issue by MichaelKlier** [CaKlassen/gmwwise#1]
Hi,

my apologies for using the issue tracker but I could find any other way to contact you. First off I'd like to thank you for the work you put into makeing Wwise available for GameMaker! 

I'd like to know if this is working in it's current state or are there any pitfalls I should watch out for (I'm not a trained programmer). 

Thanks again!
Michael

**Comment by CaKlassen** [comment]
Hey!

The version of GMWWise available on this repo isn't the most up-to-date version of the dll, and is missing the proper GameMaker scripts needed to make it operate properly.

I'm hoping to get an updated version of the dll pushed to the repo fairly soon, but I'd suggest waiting for that unless you want to poke around for yourself :)

Chris

**Comment by MichaelKlier** [comment]
Thanks for the quick reply Chris! I'll be watching this repo then :]! Thanks again for the work you're putting into this! Michael

**Comment by CaKlassen** [comment]
I've created a new release (v1.3) that officially updates GMWwise to 2014.1.5 and adds a handful of new features and learning supplements! Hope it helps.
