### ISSUE TITLE
Issue with latest Gmwwise...

### ISSUE THREAD

**Issue by doublebee022** [CaKlassen/gmwwise#10]
Updated to the latest version of GMS2 (IDE version 2.0.6.146, Runtime version 2.0.6.96).  I'm now using Wwise 2016.2.3.6077, which I believe is the prescribed version according to the manual.

Prior to using the marketplace to install the new version of Gmwwise, the old integration worked fine in the latest version of GMS2 as mentioned above.  

Deleted the old GMWwise Extension, went to the marketplace, got the new one, added it to my project, showed up in the extensions folder, so far so good.  Dropped in newly-minted banks in the included files folder.

The result:  FAILED: Run Program Complete.

Specifically:

Writing Chunk... AUDO
Writing Chunk... SCPT
Writing Chunk... DBGI
Writing Chunk... INST
Writing Chunk... LOCL
Writing Chunk... STRG
Stats : GMA : Elapsed=2074.5137
Stats : GMA : sp=570,au=0,bk=25,pt=1,sc=160,sh=5,fo=0,tl=3,ob=311,ro=27,da=30,ex=2,ma=2764,fm=0x200A21D6DEE06A4

C:\Windows\system32\cmd.exe exited with non-zero status (1)
elapsed time 00:00:08.9392643s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2.0.6.96/bin/Igor.exe" -options="C:\Users\Brian\AppData\Local\GameMakerStudio2\build.bff"  -- Windows Run started at 06/11/2017 20:50:37
FAILED: Run Program Complete

Any ideas?  I'm not sure what I missed.  (It's a bit of a blocking issue now that I've upgraded the wwise project to use 2016.2.3)

**Comment by doublebee022** [comment]
Ah! I figured it out.  This is a message to all who might experience a similar problem upgrading from old to new.

There were two old lines in my init routine from the old integration that no longer need to be there:
  
//gmwRegisterCodec(0);
//gmwRegisterPlugin(6);

Commenting these out like so solved the problem.

**Comment by CaKlassen** [comment]
Glad you figured that out! I'll admit that that should have been in the release notes. I'll update that now (If I'm able to?) Thanks for following up with the solution.
