### ISSUE TITLE
Insufficient memory to load bank?

### ISSUE THREAD

**Issue by doublebee022** [CaKlassen/gmwwise#11]
So far everything's been working fine with this integration! Until today..

I added the latest in a series of sound banks to my growing project, only to be met with the following exception:

Unable to load bank "foo":

Error (52): Insufficient memory to store bank data.

Commenting out another bank previous to "foo" stops the error, but I'm wondering why I'm getting this seeing as the profiler lists my overall bank footprint size to be ~6.8 megs.  I'm using a combination of conversion settings: Vorbis, ADPCM, and a streamed music file.  What gives?  How can less than 7 megs possibly be too big a footprint?

**Comment by doublebee022** [comment]
Also to note, this is a GMwwise exception, not a GMS2 exception.

**Comment by doublebee022** [comment]
Update: It seems to be an issue with the number of banks, not their loaded size...I consolidated the contents of 2 of my banks to 1, and now all the sounds are loading and playing.  So there seems to be some kind of limit on the number of sound banks one can have loaded at any time...is there any way around this?

**Comment by CaKlassen** [comment]
I'll look into this as soon as I can! In the mean time, a couple questions:

- Is this on Windows or Mac?
- How many banks total do you have at this point?

**Comment by doublebee022** [comment]
I think you fixed this already - sorry about the delay, been busy - here are the answers anyway for the record.
- Windows
- 16 banks total, beyond that it crashed.

**Comment by doublebee022** [comment]
Oops, spoke too soon...!

![memory_bug](https://user-images.githubusercontent.com/6504316/29262512-c28d30fa-8089-11e7-8ae2-419898bb5132.png)

It seems that I can't have more than 20 memory pools.  I'm making a pretty complex game that has to have a lot of simultaneous banks open at once...

I have 20 memory pools listed in the advanced profiler, including the stream manager, monitor, etc. as well as proper banks.

**Comment by doublebee022** [comment]
Note: I found the line of code and altered it using github's tools.  I hope I did it right, as it was my first such attempt.  I felt bad that we're all making you do the grunt work...but I'm not sure what the next steps are.

**Comment by CaKlassen** [comment]
The newest will hopefully have resolved this issue for you! Please feel free to re-open it if you continue to encounter problems :)
