### ISSUE TITLE
Is there a planned update for GM2?

### ISSUE THREAD

**Issue by cdrofenik** [CaKlassen/gmwwise#5]
Hi,
is there anything planned to support GM2?

**Comment by BrianBibbo** [comment]
Hi!

Gmwwise already supports GMS2 - I've successfully integrated it and am currently using it.  Now if only wwise was cheaper! 

I've actually been planning on adding to / updating the manual...maybe I'll get to that this weekend...anyway if you have specific questions in the meantime I'd be happy to answer them.

**Comment by cdrofenik** [comment]
Nice, actually I wanted to ask if I can somehow help along. The team I'm currently in contact with just ported the game to GM2 and they wish to use the new WWise. Are you planning on doing the update to support the new Wwise as well? If not I'd be happy to fork and update based on the new interface/documentation.

**Comment by CaKlassen** [comment]
Hey! I've got an update to the newest version in the works, but I've been delayed by other work unfortunately. I'm hoping to get it wrapped up in the near future, as well as an updated sample project in GMS2.

Once that's done, additional/more thorough documentation would definitely be a big help going forward.

**Comment by doublebee022** [comment]
I could definitely help update the documentation if you want - I didn't get to it over the weekend but I'll have time this weekend.  I've gotten through a bunch of best practices hurdles specific to GMS2 that I think would be helpful to share.  There honestly are almost no other options for sound middleware integration into GMS; this repository is literally the only thing out there that works reliably.

I'm also working on a simple program that will automatically copy your generated soundbanks into the correct place in your project, plus translate the Wwise_IDs.h file into a GMS script so you don't have to sit there manually copying event ID numbers!  I'll add that once I've gotten a bit further with it, if you guys think that would also be helpful.

**Comment by CaKlassen** [comment]
Those things sound great to add in; especially to help reduce programmers from making mistakes when exporting banks.
