### ISSUE TITLE
Music Segment not working properly

### ISSUE THREAD

**Issue by ManuelSoruco** [CaKlassen/gmwwise#6]
Greetings.
I'm working with a team on a project being done on Game Maker and I started working on the music on Wwise a few months ago. We have been trying to get our system working, but we can't do it.
My approach for the game is that instead of importing full music tracks, I'm importing single-instrument loops, and Wwise is used as a sequencer.
The level starts, the 4 tracks start playing perfectly... for about 5 seconds (as long as the first loop lasts), when the second set of loops should be being triggered, only 1 or 2 tracks play.
The song continues properly in structure, but with only 1 or 2 instruments sounding simultaneously.

I just saw today there was a sample project for Wwise as well as for GM, and when I opened it I found out that you had the music implemented as a SFX, so I wanted to know if GMWwise doesn't support music segments and that is why I can't make it work properly, or if there might be another reason.

Thanks in advance!

Ps: Using Wwise 2015.1.9, GMWwise 1.4.1 and Game Maker 1.4.1

**Comment by CaKlassen** [comment]
Hey Manuel,

In my personal project that uses GMWise, I use proper music segments and containers, so I can confirm that they are currently functional.

Have you included all streaming .wem files into your project? Other than that, I can't think of anything that would be the problem on the GMWwise side. You may want to try profiling the project if you haven't already!

**Comment by ManuelSoruco** [comment]
I managed to get it working. It was a problem with the Vorbis seektable conversion settings, that's why it was working inside Wwise (because it uses the original WAVs) but not inside the build.
Thanks for your help!
