### ISSUE TITLE
Issues with running the extension on Mac

### ISSUE THREAD

**Issue by Stewart-Bishop** [CaKlassen/gmwwise#7]
Hi there,

I noticed that your extension had the following information in your release:

"Note: Due to an ongoing issue with GameMaker: Studio 2, extensions do not always work properly when building for OSX. Please let me know if there are any issues using the Mac side of the extension in GameMaker: Studio 1.4."

So I investigated whether it worked in GMS2 and it turns out that dylib proxy files in an extension crashed our runner, we've fixed this and will be available in the next update, however once we got the extension working I received a bunch of errors with the Mac version of the extension as can be seen in these screenshots using your sample project.

![screen shot 2017-04-28 at 09 25 52](https://cloud.githubusercontent.com/assets/15923181/25521017/036e1f3c-2bf6-11e7-8b23-e0b717e5bc2e.png)
![screen shot 2017-04-28 at 09 25 47](https://cloud.githubusercontent.com/assets/15923181/25521016/036e17d0-2bf6-11e7-8562-787634cfb02d.png)
![screen shot 2017-04-28 at 09 25 44](https://cloud.githubusercontent.com/assets/15923181/25521018/036f67e8-2bf6-11e7-8f9d-85418982e571.png)
![screen shot 2017-04-28 at 09 25 38](https://cloud.githubusercontent.com/assets/15923181/25521019/036fe5d8-2bf6-11e7-83b4-19dec4d0c3dd.png)

This seems like an issue with the dylib as I receive these using GMS1 also, just thought I'd let you know.

**Comment by CaKlassen** [comment]
Hey, thanks for the help investigating (and resolving) the issue in GM:S 2!

Just to confirm, the project works fine if you use the dll on Windows with the exact same configuration? I haven't had the time to experiment too much with the dylib in 1.4, but I'll take a look and see if I can figure out what's going wrong. It's entirely possible that I've made a mistake in the source for the Mac version.

**Comment by Stewart-Bishop** [comment]
Hi there,

This was tested using your example project supplied on both Windows and Mac, Windows works fine but Mac provided the above issues.

**Comment by CaKlassen** [comment]
I've tested version 1.5.0 with my personal project on Mac now that I have access to the Mac IDE beta, and it works fine, so I'm thinking it's an issue with the sample project and not the extension itself. I should have it fixed this weekend.

**Comment by Stewart-Bishop** [comment]
Glad to hear that you're enjoying the Mac IDE Beta if you have any issues with it or your extension just post them on the Support Forum and we'll take a look.

Feel free to close this at any time as it has served its purpose now that you've found the cause of the issue.
