### ISSUE TITLE
Question about Version 1.5.0

### ISSUE THREAD

**Issue by Fingus** [CaKlassen/gmwwise#8]
Hello, great work with the plugin btw. 

Does Version 1.5.0 work with GMS-1.4 or is it only for GM2?

Thanks in advance

**Comment by CaKlassen** [comment]
The documentation/support for 1.5 going forward target GM:S2 primarily, but you should be able to do one of a couple of things:

1. (If this works like I remember it) Download the GMWwise extension from the Marketplace through Studio 1.4, as well as the GMWwise 1.5 release from GitHub (for the profile/release DLL and DYLIB files)

2. Use an older release and replace the DLL/DYLIB files in your GameMaker project with the ones provided in 1.5

Hopefully that helps!

**Comment by tadashibashi** [comment]
For some reason, the GMWwise extension plugin doesn't appear in the marketplace in Game Maker Studio 1.4. Is there a distinction between the marketplaces of 1.4 and 2?

**Comment by CaKlassen** [comment]
I just confirmed this and, unfortunately, it looks like something must have changed in extensions between 1.4 and 2, so the marketplace has separate listings for GMWwise. I plan to release a new version this weekend, and I will do my best to upload a 1.4 version to the marketplace at the same time.

**Comment by CaKlassen** [comment]
With the release of GMWwise 1.5.1, you should be able to include the extension into your GameMaker: Studio 1.4 project. Please re-open this issue if you are unable to do so :)
